version: '3'
services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /app:/app
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: noka-cms
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
    links:
      - mongo:mongo
    volumes:
      - ./api:/srv/app
    ports:
      - '1337:1337'
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
